name: CI/CD Pipeline

on:
  push:
    branches:
      - deploy-imane

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: dev
          POSTGRES_PASSWORD: dev
          POSTGRES_DB: messengerdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./Back
        run: npm install

      - name: Generate Prisma client
        working-directory: ./Back
        run: npx prisma generate

      - name: Build Nest.js
        working-directory: ./Back
        run: npm run build

      - name: Run unit tests
        working-directory: ./Back
        run: npm run test

      - name: Install Newman
        run: npm install -g newman

      - name: Start Nest.js in background
        working-directory: ./Back
        run: |
          npm run start:dev &
          sleep 10

      - name: Run Postman integration tests
        run: newman run postman/collection.json --env-var baseUrl=localhost:3000


      - name: Docker build backend
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/projet-web-back:latest ./Back

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/projet-web-back:latest
